// <auto-generated>
// このファイルは自動生成されています。
// コードを修正する際は、このファイルは修正せず、*.ttファイルを修正して下さい。
// </auto-generated>
using System;
 
namespace T4.DesigneTime
{
    public sealed class T4SampleInt16
    {
        public static readonly T4SampleInt16 Instance = new T4SampleInt16();

        private T4SampleInt16()
        {
        }
 
        public Int16 ToInt16(string value)
            => Int16.Parse(value);
    }
 
    public sealed class T4SampleInt32
    {
        public static readonly T4SampleInt32 Instance = new T4SampleInt32();

        private T4SampleInt32()
        {
        }
 
        public Int32 ToInt32(string value)
            => Int32.Parse(value);
    }
 
    public sealed class T4SampleInt64
    {
        public static readonly T4SampleInt64 Instance = new T4SampleInt64();

        private T4SampleInt64()
        {
        }
 
        public Int64 ToInt64(string value)
            => Int64.Parse(value);
    }
 
    public sealed class T4SampleUInt16
    {
        public static readonly T4SampleUInt16 Instance = new T4SampleUInt16();

        private T4SampleUInt16()
        {
        }
 
        public UInt16 ToUInt16(string value)
            => UInt16.Parse(value);
    }
 
    public sealed class T4SampleUInt32
    {
        public static readonly T4SampleUInt32 Instance = new T4SampleUInt32();

        private T4SampleUInt32()
        {
        }
 
        public UInt32 ToUInt32(string value)
            => UInt32.Parse(value);
    }
 
    public sealed class T4SampleUInt64
    {
        public static readonly T4SampleUInt64 Instance = new T4SampleUInt64();

        private T4SampleUInt64()
        {
        }
 
        public UInt64 ToUInt64(string value)
            => UInt64.Parse(value);
    }
 
    public sealed class T4SampleByte
    {
        public static readonly T4SampleByte Instance = new T4SampleByte();

        private T4SampleByte()
        {
        }
 
        public Byte ToUInt8(string value)
            => Byte.Parse(value);
    }
 
    public sealed class T4SampleSByte
    {
        public static readonly T4SampleSByte Instance = new T4SampleSByte();

        private T4SampleSByte()
        {
        }
 
        public SByte ToInt8(string value)
            => SByte.Parse(value);
    }
 
}